### ISSUE TITLE
Support for requests from file URL for startUrls

### ISSUE THREAD

**Issue by drobnikj** [vdrmota/Social-Media-and-Contact-Info-Extractor#4]
Scraper can not work with requestsFromUrl in startUrls params.
Example input:
```
{
  "startUrls": [
    {
      "requestsFromUrl": "https://apify-uploads-prod.s3.amazonaws.com/files-with-urls.txt"
    }
  ],
  "proxyConfig": {
    "useApifyProxy": true
  },
  "maxDepth": 2,
  "maxRequests": 100,
  "sameDomain": false,
  "liveView": false,
  "considerChildFrames": true
}
```

Run with this input failed:
```
2019-07-19T13:03:45.052Z ERROR: The function passed to Apify.main() threw an exception: (error details: type=invalid-parameter)
2019-07-19T13:03:45.053Z   ApifyClientError: Parameter "url" of type String must be provided
2019-07-19T13:03:45.055Z     at exports.checkParamOrThrow (/home/myuser/node_modules/apify-client/build/utils.js:222:15)
2019-07-19T13:03:45.056Z     at new Request (/home/myuser/node_modules/apify/build/request.js:137:34)
2019-07-19T13:03:45.058Z     at input.startUrls.map (/home/myuser/src/main.js:16:21)
2019-07-19T13:03:45.059Z     at Array.map (<anonymous>)
2019-07-19T13:03:45.061Z     at Apify.main (/home/myuser/src/main.js:15:35)
2019-07-19T13:03:45.062Z     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by drobnikj** [comment]
Fixed: https://github.com/vdrmota/Social-Media-and-Contact-Info-Extractor/commit/a1a99c816fecc418e3c20c895eb44465e1a87200
